### ISSUE TITLE
Generated Contentful types are all nullable

### ISSUE THREAD

**Issue by bsgreenb** [wataruoguchi/gatsby-starter-typescript-contentful#1]
If you're doing a static build, isn't it preferable that some fields are non_nullable?  Seems like you have to null check every contentful field cus they're all wrapped in `Maybe`

**Comment by wataruoguchi** [comment]
Hi @bsgreenb, thanks for the question. Actually, https://graphql-code-generator.com/ is the one that determines whether those fields are nullable or not. I'd read their documents and ask them.

Personally, I *think*, because the graphql query doesn't always request those MAYBE fields (for example, it only requests 4-5 fields in my query), the generated file is trying to be more flexible. TypeScript allows you to create your own type, and that's pretty easy. If you need a type that is more strict, you can create the type and unite with the generated type.

Hope it makes sense.

Best,

**Comment by bsgreenb** [comment]
I've been taking the approach you recommended, though to make nested fields required is a lot of manual work. Nested entries, assets, rich text embeds all require special overrides.  It works but I imagine the framework could deliver something better and more cohesive for gatsby/contentful/typescript use case.

Here's gist of the type of type facading you have to do with this approach:
https://gist.github.com/bsgreenb/05202d74c7ef079970b536fad0fc5c88

**Comment by wataruoguchi** [comment]
@bsgreenb Here's the library this project is using: https://github.com/dotansimha/graphql-code-generator
It looks like the GraphQL schema is causing the issue. The following chunks are from README.

```
type Author {
  id: Int!
  firstName: String!
  lastName: String!
  posts(findTitle: String): [Post]
}
```

If you define the schema like this above, that'd be:

```
export type Scalars = {
  ID: string,
  String: string,
  Boolean: boolean,
  Int: number,
  Float: number,
};

export type Author = {
  __typename?: 'Author',
  id: Scalars['Int'],
  firstName: Scalars['String'],
  lastName: Scalars['String'],
  posts?: Maybe<Array<Maybe<Post>>>,
};
```

My hypothesis is that if you can manage the schema somehow, we could resolve this issue.
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

It was an interesting discovery. I'd add this explicit schema type definition in the example if I had time.

**Comment by bsgreenb** [comment]
@wataruoguchi I am also using graphql-code-generator

The challenge is that generated contentful models are all wrapped in Maybe.  Here's an example of the export:

```
export type ContentfulPost = Node & {
   __typename?: 'ContentfulPost';
  id: Scalars['ID'];
  parent?: Maybe<Node>;
  children: Array<Node>;
  internal: Internal;
  title?: Maybe<Scalars['String']>;
  slug?: Maybe<Scalars['String']>;
  postType?: Maybe<Scalars['String']>;
  featuredImage?: Maybe<ContentfulAsset>;
  author?: Maybe<ContentfulAuthor>;
  category?: Maybe<ContentfulCategory>;
  body?: Maybe<ContentfulPostBodyRichTextNode>;
  spaceId?: Maybe<Scalars['String']>;
  contentful_id?: Maybe<Scalars['String']>;
  createdAt?: Maybe<Scalars['Date']>;
  updatedAt?: Maybe<Scalars['Date']>;
  sys?: Maybe<ContentfulPostSys>;
  node_locale?: Maybe<Scalars['String']>;
  subTitle?: Maybe<Scalars['String']>;
  childContentfulPostBodyRichTextNode?: Maybe<ContentfulPostBodyRichTextNode>;
};
```

I'll also add you to the repo, where you could see in /src/types/ what I'm dealing with as well as codegen config etc.  Let me know if anything else required
