### ISSUE TITLE
Where are the types?

### ISSUE THREAD

**Issue by Elyx0** [wataruoguchi/gatsby-starter-typescript-contentful#125]
import { BlogPagesQueryQuery } from '../../types/graphql-types'; // eslint-disable-line import/no-unresolved

I don't understand how I'm supposed to find them Is it extracted from the same file?

**Comment by Elyx0** [comment]
Actually more than that I had the bad idea to update and received:
```
failed We've encountered an error: Objects are not valid as a React child (found: GraphQLDocumentError:
GraphQLDocumentError: Unknown type "ContentfulFixed". Did you mean "ContentfulBlogPost",
"ContentfulBlogPostEdge", or "ContentfulContentType"?). If you meant to render a collection of children, use an
 array instead.
```

I created everything needed in contentful

**Comment by wataruoguchi** [comment]
Hi @Elyx0 ,

The file `graphql-types` is defined in https://github.com/wataruoguchi/gatsby-starter-typescript-contentful/blob/2419b01721e1ef6668c85339af410003c8513dad/gatsby-config.js#L44 and is generated by https://www.npmjs.com/package/gatsby-plugin-graphql-codegen .
